# Generated by Django 4.1.13 on 2023-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=500)),
                ('nick_text', models.CharField(max_length=500)),
                ('department_text', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('building_number', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('photo', models.ImageField(default='', max_length=255, upload_to='image/%Y/%m/%d/')),
            ],
        ),
    ]
