# Generated by Django 4.1.13 on 2023-11-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='photo',
            new_name='image',
        ),
    ]
