# Generated by Django 4.1.13 on 2023-11-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0004_alter_info_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='image',
            new_name='photo',
        ),
    ]
