# Generated by Django 4.1.13 on 2023-12-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0005_rename_image_info_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
