# Generated by Django 4.1.13 on 2023-12-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuapp', '0006_alter_info_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
